<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{


    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('embeddings', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->softDeletes();
            // Text to be sent to Gemini for embedding (generated by seeder)
            $table->text('text_for_llm_embedding');

            // The actual embedding vector from Gemini (populated by a separate command/job)
            $table->json('embedding_vector')->nullable();
            $table->nullableMorphs('embeddable');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('embeddings');
    }
};
